Update to ROCm4.2
pytorch/ossci-job-dsl pull request #103
Opened 2021-05-11 06:34 UTC by jithunnair-amd

2021-05-13 13:58 UTC, ezyang approved these changes

2021-05-27 22:10 UTC, jithunnair-amd commented
@seemethere We should be ready to move ROCm CI to 4.2 now

2021-05-27 22:20 UTC, jeffdaily requested changes
`DOCKER_TAG=$(git rev-parse HEAD:.circleci/docker)` has changed since PR was submitted.

2152ba6309b12251994fcdcd4ff234bfbe646d06

2021-05-27 22:20 UTC, jeffdaily commented on src/main/groovy/ossci/caffe2/DockerVersion.groovy
> +  static final String version = "cf0725f072e1d52d34c23d848a906fbc4dee44f6";  // WARNING: if you change this to a new version number, you **MUST** also add that version number to the allDeployedVersio
```suggestion
  static final String version = "2152ba6309b12251994fcdcd4ff234bfbe646d06";  // WARNING: if you change this to a new version number, you **MUST** also add that version number to the allDeployedVersions list below
```

2021-05-27 22:20 UTC, jeffdaily commented on src/main/groovy/ossci/pytorch/DockerVersion.groovy
> +  static final String version = "cf0725f072e1d52d34c23d848a906fbc4dee44f6";
```suggestion
  static final String version = "2152ba6309b12251994fcdcd4ff234bfbe646d06";
```

2021-05-27 22:35 UTC, merged